apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zetl
  namespace: zetl
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - zetl.zachmonroe.cloud
      secretName: zetl-tls
  rules:
    - host: zetl.zachmonroe.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zetl
                port:
                  name: http
