apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zetl

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- cluster-issuer.yaml

images:
- name: zachmonroe/zetl
  newName: zachmonroe/zetl
  newTag: 032d779

labels:
- pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zetl
