apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zetl

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cluster-issuer.yaml

images:
  - name: zachmonroe/zetl
    newTag: latest

labels:
  - pairs:
      app.kubernetes.io/name: zetl
      app.kubernetes.io/managed-by: kustomize
