apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zetl

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

secretGenerator:
  - name: zetl-secrets
    envs:
      - .env

generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/name: zetl
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
